version: "3.8"

networks:
  silver_map_network:
    driver: bridge

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres_prod
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - silver_map_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/askarkasimov/silver-map-api:latest
    container_name: silver_backend_prod
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@postgres_prod:5432/${PG_DB}
    ports:
      - "8000:8000"
    depends_on:
      postgres_prod:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - silver_map_network

volumes:
  postgres_data:
