networks:
  silver_map_network:
    driver: bridge

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - silver_map_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:11.8.1
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:5432/${PG_DB} -user=${PG_USER} -password=${PG_PASSWORD} -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
      - ./db_init_scripts:/flyway/sql
    networks:
      - silver_map_network

  api:
    image: ghcr.io/askarkasimov/silver-map-api:latest
    pull_policy: always
    container_name: silver_backend_prod
    environment:
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}
      - APP_MODE=production
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - silver_map_network

volumes:
  postgres_data:
